### ISSUE TITLE
Django 1.11 and email sending

### ISSUE THREAD

**Issue by cristianocca** [Suor/handy#15]
https://github.com/Suor/handy/blob/master/handy/mail.py#L45

That line won't work properly since render_to_string signature was updated, it should instead pass the request as the third parameter and a an empty dict as a context, currently it will make any context processor that relies on it to fail/crash since it is expecting a request object.

**Comment by cristianocca** [comment]
Thanks! Is this something you will be pushing to pypi soon?

**Comment by Suor** [comment]
Released. I let code cool a bit usually for a few days)
