### ISSUE TITLE
@Ajax decorator and json serialization

### ISSUE THREAD

**Issue by cristianocca** [Suor/handy#16]
Currently `@ajax` and `render_to_json` uses two different json encoders, one that uses a very old datetime format (the @ajax one) and another one that uses datetime isoformat (which should be fine to meet current javascript date formatting).

Would be great to have all json serialization code to use the same encoder, and even better, use the django one (DjangoJSONEncoder) that's already implemented to handle all non standard data types.

**Comment by Suor** [comment]
I see. Unifying them is a good idea laid aside for maybe too long.

Switching to `DjangoJSONEncoder` will be not backwards compatible, but maybe a good idea anyway.

**Comment by cristianocca** [comment]
Perhaps the @Ajax decorator could take an encoder in case someone really needs the old encoder. But if I'm not wrong the only difference is the datetime serialization which nowdays anyone should be using ISO format anyways.

**Comment by Suor** [comment]
Fixed in aa44bc80846892acf3c1e1ddea4de6f4a409dc39. Using DjangoJSONEncoder in both places now. Old behavior is removed. Anyone needing it to open new issue and justify.
